DROP TABLE IF EXISTS question_attempts;
DROP TABLE IF EXISTS test_results;
DROP TABLE IF EXISTS test_questions;
DROP TABLE IF EXISTS question_tags;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS questions;
DROP TABLE IF EXISTS tests;
DROP TABLE IF EXISTS courses;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS users;

-- DROP ENUMS

DROP TYPE IF EXISTS QUESTION_SCOPE;
DROP TYPE IF EXISTS TEST_SCOPE;
DROP TYPE IF EXISTS USER_ROLE;

-- DROP EXTENSION (optional)

DROP EXTENSION IF EXISTS "uuid-ossp";
