version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: mock-db
    restart: always
    env_file:
      - ../.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../internal/database/migrations:/docker-entrypoint-initdb.d

  api:
    image: mock-api
    container_name: mock-api
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    restart: always

  nginx:
    image: nginx:alpine
    container_name: mock-nginx
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always

volumes:
  postgres_data:

