// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/tests": {
            "get": {
                "description": "Retrieves a list of all tests ordered by creation date (oldest first)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tests"
                ],
                "summary": "List all tests",
                "responses": {
                    "200": {
                        "description": "List of tests retrieved successfully",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handler.Test"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new test under a specified course with default duration of 2 hours (7200 seconds)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tests"
                ],
                "summary": "Create a new test",
                "parameters": [
                    {
                        "description": "Test creation details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateTestRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Test created successfully",
                        "schema": {
                            "$ref": "#/definitions/handler.Test"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or missing required fields",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Course not found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Validation errors",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tests/{test_id}": {
            "get": {
                "description": "Retrieves detailed information about a specific test including title, description, question count, and time limit",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tests"
                ],
                "summary": "Get a test metadata by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Test ID",
                        "name": "test_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Test found successfully",
                        "schema": {
                            "$ref": "#/definitions/handler.Test"
                        }
                    },
                    "404": {
                        "description": "Test not found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Updates the title and maximum time allowed for a test",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tests"
                ],
                "summary": "Update test metadata",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Test ID",
                        "name": "test_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Test update details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UpdateTestRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Test updated successfully",
                        "schema": {
                            "$ref": "#/definitions/utils.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or validation failed",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Test not found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tests/{test_id}/questions": {
            "get": {
                "description": "Retrieves all questions assigned to a test in their specified order, including question text, options, difficulty, and tags",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tests"
                ],
                "summary": "Get test questions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Test ID",
                        "name": "test_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                " questions": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/QuestionResponse"
                                    }
                                },
                                " total_questions": {
                                    "type": "number"
                                },
                                "test_id": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid test ID",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Replaces all questions for a test with a new set. Existing questions are removed and new ones are added in the specified order. Pass an empty array to clear all questions.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tests"
                ],
                "summary": "Assign questions to test",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Test ID",
                        "name": "test_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Question IDs to assign",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/AssignQuestionsInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Questions assigned successfully",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "test_id": {
                                    "type": "string"
                                },
                                "total_questions": {
                                    "type": "integer"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid request body or validation failed",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Test not found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tests/{test_id}/start": {
            "post": {
                "description": "Starts a test session for a user, records start time, calculates and stores the absolute end time",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tests"
                ],
                "summary": "Start a test",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Test ID",
                        "name": "test_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Test started successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Test not found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "AssignQuestionsInput": {
            "type": "object",
            "required": [
                "question_ids"
            ],
            "properties": {
                "question_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "aB3xK9mP",
                        "xK9mPaB3"
                    ]
                }
            }
        },
        "CreateTestRequest": {
            "type": "object",
            "required": [
                "course_id",
                "title"
            ],
            "properties": {
                "course_id": {
                    "type": "string",
                    "example": "123e4567"
                },
                "description": {
                    "type": "string",
                    "maxLength": 250,
                    "example": "This is test description"
                },
                "title": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3,
                    "example": "Test Title"
                }
            }
        },
        "QuestionResponse": {
            "type": "object",
            "properties": {
                "content_hash": {
                    "type": "string",
                    "example": "b48922ecd8a1590f08ce412a35a72480"
                },
                "diagram_url": {
                    "type": "string",
                    "example": "false"
                },
                "difficulty": {
                    "type": "string",
                    "example": "easy"
                },
                "explanation": {
                    "type": "string",
                    "example": "Basic arithmetic"
                },
                "has_latex": {
                    "type": "boolean",
                    "example": false
                },
                "id": {
                    "type": "string",
                    "example": "aB3xK9mP"
                },
                "options": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "2",
                        "3",
                        "4",
                        "5"
                    ]
                },
                "question_text": {
                    "type": "string",
                    "example": "What is 2 + 2?"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "math",
                        "arithmetic"
                    ]
                }
            }
        },
        "UpdateTestRequest": {
            "type": "object",
            "required": [
                "max_time_seconds",
                "title"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 250,
                    "example": "Update test description"
                },
                "max_time_seconds": {
                    "type": "integer",
                    "minimum": 60,
                    "example": 9000
                },
                "title": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3,
                    "example": "Updated Test Title"
                }
            }
        },
        "handler.Test": {
            "type": "object",
            "properties": {
                "course_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "max_time_seconds": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "total_questions": {
                    "type": "integer"
                }
            }
        },
        "utils.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {
                    "type": "object",
                    "additionalProperties": true
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "utils.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Mock API",
	Description:      "Mock backend",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
